- Pipfile
- Pipfile.lock
- app.py
- pelican/avro/export.py
- pelican/dictionary.py
When some file node were linked with only optional links, the bfs won’t grab the files, dfs is better for all the dictionaries (including this scenario).
> Fix for missing files

- job_export.py
- pelican/dictionary.py
- pelican/graphql/guppy_gql.py
- pelican/jobs.py
* Fix the performance issue;
* Fix the Guppy `/download` endpoint query.
> Performance fix

- job_import.py
- pelican/jobs.py
- Unused environmental variable
- Do not remove temporary file immediately
- Spark issue
- Use sheepdog credentials
> Fixes for Spark, temporary files and environmental variables

- pelican/jobs.py
- fix upward nodes doesn't have `relations`
> fix(pelican): upward nodes on export missing relations

- pelican/jobs.py
- Implemented topological order for nodes
> feat: make topological order for exported nodes

- pelican/dictionary.py
- Fixes the order from pure dfs to topological
> fix: topology order of nodes

- README.md
> chore(qa): Add documentation related to the release process

- .pre-commit-config.yaml
- .secrets.baseline
Confirmed that there are no secrets in this file. The baseline secret audit only flagged a hex in the pipenv.lock file.
> pre commit hooks and baseline secrets

- Pipfile.lock
> dep: update Pipfile.lock

- .github/workflows/release.yaml
- install python 3.8 in github action for release
> updating release action to include update to python

- .github/workflows/release.yaml
Fixed github token definition for release action
> changing github token variable in action

- README.md
- updating readme for new release
> updating readme for new release

- .github/workflows/release.yaml
- fixed all instances of github action tokens
> fixing all github tokens

- README.md
- Updating readme and releasing
> updating readme for a new release

- Pipfile.lock
> fix(lockfile): regenerate Pipfile lock

- .github/workflows/release.yaml
- poetry.lock
Set py 3.7 for release automation logic
> fix(gh-action-release): Set py 3.7 for release automation logic

- README.md
- Add docs about EXTRA_NODES config
> docs(EXTRA_NODES): add docs/example for config

- poetry.lock
- pyproject.toml
https://occ-data.atlassian.net/browse/COV-875
- Fix encoding issue when exporting
> use latest version of pypfb to fix encoding

- export.Dockerfile
- import.Dockerfile
new base image for docker files to update lets encrypt certs
> updating docker files for new certificits

- export.Dockerfile
- import.Dockerfile
reverting base image change
installing ca-cartificates
reverting java update
> reverting image change and java change

- pelican/jobs.py
- don't attempt to query if id_chunks is False-y for whatever reason (as this causes an exception)
> fix(get): don't attempt to query if id_chunks is False-y for whatever reason (as this causes an exception)

- pelican/jobs.py
Make it more clear what this debug log is printing
> Update debug log

- job_export.py
- Fence client is not required if access_format != "guid"
> Fence client is not required if access_format != "guid"

- pelican/graphql/base_gql.py
- pelican/graphql/guppy_gql.py
- pelican/s3.py
- Fixes issue with pelican that prevented PFBs with more than 10k entries from being created.
> Fixes download fallback
